apiVersion: v1
kind: Service
metadata:
  name: remix-on-spaceship-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: remix-on-spaceship-demo
